openapi: 3.1.0
info:
  title: API spec, mainly for client generation
  version: 0.0.1
paths:
  "/api/items":
    get:
      summary: Get items list
      operationId: items
      tags:
        - Items
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ItemBase"

  "/api/cached_items":
    get:
      summary: Get cached items list
      operationId: cached_items
      tags:
        - CachedItems
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ItemBase"

    post:
      summary: Create new CachedItem
      operationId: create
      tags:
        - CachedItems
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                item_id:
                  type: string
                  format: uuid
                parent_id:
                  type: string
                  format: uuid
                value:
                  type: string
              required:
                - parent_id
                - value
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ItemBase"

  "/api/cached_items/load":
    post:
      summary: Load Item to CachedItem
      operationId: load
      tags:
        - CachedItems
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                item_id:
                  type: string
                  format: uuid
              required:
                - item_id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ItemBase"

  "/api/cached_items/{id}":
    parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
    patch:
      summary: Update CachedItem
      operationId: update
      tags:
        - CachedItems
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  type: string
              required:
                - value
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ItemBase"
    delete:
      summary: Mark CachedItem as deleted
      operationId: remove
      tags:
        - CachedItems
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ItemBase"

components:
  schemas:
    ItemBase:
      type: object
      properties:
        id:
          type: string
          format: uuid
        parent_id:
          type: [ string, 'null' ]
          format: uuid
        value:
          type: string
        created_at:
          type: string
          format: date_time
        updated_at:
          type: string
          format: date_time
      required:
        - id
        - parent_id
        - value

    OperationBase:
      type: object
      properties:
        id:
          type: string
          format: uuid
        data:
          type: object
          properties:
            id:
              type: string
              format: uuid
          required:
            - id
        created_at:
          type: string
          format: date_time
        updated_at:
          type: string
          format: date_time
      required:
        - id
        - created_at
        - updated_at
