services:
  web:
    image: kirill00sa/tree_replication
    build:
      context: ../../web
    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
